// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bgs/low/pb/client/global_extensions/message_options.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fmessage_5foptions_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fmessage_5foptions_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/descriptor.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fmessage_5foptions_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fmessage_5foptions_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fmessage_5foptions_2eproto;
namespace bgs {
namespace protocol {
class BGSMessageOptions;
class BGSMessageOptionsDefaultTypeInternal;
extern BGSMessageOptionsDefaultTypeInternal _BGSMessageOptions_default_instance_;
}  // namespace protocol
}  // namespace bgs
PROTOBUF_NAMESPACE_OPEN
template<> ::bgs::protocol::BGSMessageOptions* Arena::CreateMaybeMessage<::bgs::protocol::BGSMessageOptions>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace bgs {
namespace protocol {

// ===================================================================

class BGSMessageOptions :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bgs.protocol.BGSMessageOptions) */ {
 public:
  BGSMessageOptions();
  virtual ~BGSMessageOptions();

  BGSMessageOptions(const BGSMessageOptions& from);
  BGSMessageOptions(BGSMessageOptions&& from) noexcept
    : BGSMessageOptions() {
    *this = ::std::move(from);
  }

  inline BGSMessageOptions& operator=(const BGSMessageOptions& from) {
    CopyFrom(from);
    return *this;
  }
  inline BGSMessageOptions& operator=(BGSMessageOptions&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const BGSMessageOptions& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BGSMessageOptions* internal_default_instance() {
    return reinterpret_cast<const BGSMessageOptions*>(
               &_BGSMessageOptions_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(BGSMessageOptions& a, BGSMessageOptions& b) {
    a.Swap(&b);
  }
  inline void Swap(BGSMessageOptions* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline BGSMessageOptions* New() const final {
    return CreateMaybeMessage<BGSMessageOptions>(nullptr);
  }

  BGSMessageOptions* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<BGSMessageOptions>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const BGSMessageOptions& from);
  void MergeFrom(const BGSMessageOptions& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BGSMessageOptions* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bgs.protocol.BGSMessageOptions";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fmessage_5foptions_2eproto);
    return ::descriptor_table_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fmessage_5foptions_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCustomSelectShardFieldNumber = 1,
    kCustomValidatorFieldNumber = 2,
    kClientIdFanoutFieldNumber = 3,
  };
  // optional bool custom_select_shard = 1;
  bool has_custom_select_shard() const;
  private:
  bool _internal_has_custom_select_shard() const;
  public:
  void clear_custom_select_shard();
  bool custom_select_shard() const;
  void set_custom_select_shard(bool value);
  private:
  bool _internal_custom_select_shard() const;
  void _internal_set_custom_select_shard(bool value);
  public:

  // optional bool custom_validator = 2;
  bool has_custom_validator() const;
  private:
  bool _internal_has_custom_validator() const;
  public:
  void clear_custom_validator();
  bool custom_validator() const;
  void set_custom_validator(bool value);
  private:
  bool _internal_custom_validator() const;
  void _internal_set_custom_validator(bool value);
  public:

  // optional bool client_id_fanout = 3;
  bool has_client_id_fanout() const;
  private:
  bool _internal_has_client_id_fanout() const;
  public:
  void clear_client_id_fanout();
  bool client_id_fanout() const;
  void set_client_id_fanout(bool value);
  private:
  bool _internal_client_id_fanout() const;
  void _internal_set_client_id_fanout(bool value);
  public:

  // @@protoc_insertion_point(class_scope:bgs.protocol.BGSMessageOptions)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  bool custom_select_shard_;
  bool custom_validator_;
  bool client_id_fanout_;
  friend struct ::TableStruct_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fmessage_5foptions_2eproto;
};
// ===================================================================

static const int kMessageOptionsFieldNumber = 90000;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::MessageTypeTraits< ::bgs::protocol::BGSMessageOptions >, 11, false >
  message_options;

// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BGSMessageOptions

// optional bool custom_select_shard = 1;
inline bool BGSMessageOptions::_internal_has_custom_select_shard() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool BGSMessageOptions::has_custom_select_shard() const {
  return _internal_has_custom_select_shard();
}
inline void BGSMessageOptions::clear_custom_select_shard() {
  custom_select_shard_ = false;
  _has_bits_[0] &= ~0x00000001u;
}
inline bool BGSMessageOptions::_internal_custom_select_shard() const {
  return custom_select_shard_;
}
inline bool BGSMessageOptions::custom_select_shard() const {
  // @@protoc_insertion_point(field_get:bgs.protocol.BGSMessageOptions.custom_select_shard)
  return _internal_custom_select_shard();
}
inline void BGSMessageOptions::_internal_set_custom_select_shard(bool value) {
  _has_bits_[0] |= 0x00000001u;
  custom_select_shard_ = value;
}
inline void BGSMessageOptions::set_custom_select_shard(bool value) {
  _internal_set_custom_select_shard(value);
  // @@protoc_insertion_point(field_set:bgs.protocol.BGSMessageOptions.custom_select_shard)
}

// optional bool custom_validator = 2;
inline bool BGSMessageOptions::_internal_has_custom_validator() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool BGSMessageOptions::has_custom_validator() const {
  return _internal_has_custom_validator();
}
inline void BGSMessageOptions::clear_custom_validator() {
  custom_validator_ = false;
  _has_bits_[0] &= ~0x00000002u;
}
inline bool BGSMessageOptions::_internal_custom_validator() const {
  return custom_validator_;
}
inline bool BGSMessageOptions::custom_validator() const {
  // @@protoc_insertion_point(field_get:bgs.protocol.BGSMessageOptions.custom_validator)
  return _internal_custom_validator();
}
inline void BGSMessageOptions::_internal_set_custom_validator(bool value) {
  _has_bits_[0] |= 0x00000002u;
  custom_validator_ = value;
}
inline void BGSMessageOptions::set_custom_validator(bool value) {
  _internal_set_custom_validator(value);
  // @@protoc_insertion_point(field_set:bgs.protocol.BGSMessageOptions.custom_validator)
}

// optional bool client_id_fanout = 3;
inline bool BGSMessageOptions::_internal_has_client_id_fanout() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool BGSMessageOptions::has_client_id_fanout() const {
  return _internal_has_client_id_fanout();
}
inline void BGSMessageOptions::clear_client_id_fanout() {
  client_id_fanout_ = false;
  _has_bits_[0] &= ~0x00000004u;
}
inline bool BGSMessageOptions::_internal_client_id_fanout() const {
  return client_id_fanout_;
}
inline bool BGSMessageOptions::client_id_fanout() const {
  // @@protoc_insertion_point(field_get:bgs.protocol.BGSMessageOptions.client_id_fanout)
  return _internal_client_id_fanout();
}
inline void BGSMessageOptions::_internal_set_client_id_fanout(bool value) {
  _has_bits_[0] |= 0x00000004u;
  client_id_fanout_ = value;
}
inline void BGSMessageOptions::set_client_id_fanout(bool value) {
  _internal_set_client_id_fanout(value);
  // @@protoc_insertion_point(field_set:bgs.protocol.BGSMessageOptions.client_id_fanout)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol
}  // namespace bgs

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fmessage_5foptions_2eproto
